run-name: Build Android
on: workflow_dispatch

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.18.1"
          registry-url: "https://npm.pkg.github.com"
          scope: '@ridetracker'

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      # Skip post-install scripts here, as a malicious script could steal NODE_AUTH_TOKEN.
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # `npm rebuild` will run all those post-install scripts for us.
      - name: Run post-install scripts
        run: "npm rebuild && npm run prepare --if-present"
        shell: bash
        
