run-name: Build Android
on: workflow_dispatch

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-20.04
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"  
          scope: "@ridetracker"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

